In [3]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [5]:
np.cumsum(a, dtype=float)    # specifies type of output value(s)

array([ 1.,  3.,  6., 10., 15., 21.])

In [8]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
np.cumsum(a)

array([  3,   8,  15,  17,  25,  35,  46, 111, 183, 264, 363, 463, 613],
      dtype=int32)

In [18]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    #print(ret)
    #print(ret[n:])
    #print(ret[:-n])
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(a, n=3))


[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [24]:
import numpy as np
X=np.array([1,2,3,4,5])
X
N=5
matrix=np.column_stack([X**(N-i-1)for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [27]:
X=np.array([1,2,3,4,5])
N=5
matrix=np.vander(X,N,increasing=False)
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [28]:
#The determinent for matrix
np.linalg.det(matrix)

287.9999999999977